// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using loan_management_system.Model;

#nullable disable

namespace loan_management_system.Migrations
{
    [DbContext(typeof(LoanContext))]
    [Migration("20260613115625_FixLoanCustomerForeignKey")]
    partial class FixLoanCustomerForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("loan_management_system.Model.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreditScore")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PersonNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("loan_management_system.Model.LoanSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LoansID")
                        .HasColumnType("int");

                    b.Property<double>("PMT")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.HasIndex("LoansID");

                    b.ToTable("LoanSchedule");
                });

            modelBuilder.Entity("loan_management_system.Model.Loans", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double");

                    b.Property<double>("MonthlyPayment")
                        .HasColumnType("double");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("loan_management_system.Model.Payments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int>("LoansID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("LoansID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("loan_management_system.Model.LoanSchedule", b =>
                {
                    b.HasOne("loan_management_system.Model.Loans", "Loans")
                        .WithMany("LoanSchedule")
                        .HasForeignKey("LoansID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("loan_management_system.Model.Loans", b =>
                {
                    b.HasOne("loan_management_system.Model.Customers", "Customers")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("loan_management_system.Model.Payments", b =>
                {
                    b.HasOne("loan_management_system.Model.Loans", "Loans")
                        .WithMany("Payments")
                        .HasForeignKey("LoansID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("loan_management_system.Model.Customers", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("loan_management_system.Model.Loans", b =>
                {
                    b.Navigation("LoanSchedule");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
